server:
  port: 8040


spring:
  # 服务名称
  application:
    name: alien-client

  cloud:
    nacos:
      discovery:
        # nacos注册地址
        server-addr: 127.0.0.1:8848
        # 命名空间-环境隔离
#        namespace: 8cbc89ee-5db3-43a1-8f95-176596a61ee0
        # 集群名称
#        cluster-name: alien

