# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nuc8i7.wcj.plus:3306/abac?useruseUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: weichangjin
